### ISSUE TITLE
Attestation signing submission is failing 

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#33] opened 2022-03-20 10:40 UTC
There are multiple errors occurring and very frequently.
i was using it since 1 year we were getting errors but now from 5th of march getting almost always the below errors.

Attestation Submission

> Create Product
    * Create JSON
    * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option
Unhandled Exception:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.Utility.AuthorizationHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<HdcPost>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<NewProduct>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in E:\Home\mtk20241\Attestation_task\SDCM-main_1\SDCM-main\SurfaceDevCenterManager\Program.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SurfaceDevCenterManager.Program.Main(String[] args) in E:\Home\mtk20241\Attestation_task\SDCM-main_1\SDCM-main\SurfaceDevCenterManager\Program.cs:line 60
Last Command:
ERROR (DevCenterErrorDetails)
Code:    
HttpCode:
Message: 
Correlation Id: d1cc9a7c-280e-4977-a10b-16fd4a7c1f63
Request Id:     13c7c7ce-3a66-4095-ba90-34dd198c9521
Method:         POST
Url:            https://manage.devcenter.microsoft.com/v2.0/my/hardware/products
Content:        {"productName":"mediatek_driver_Attestation","testHarness":"Attestation","announcementDate":"2020-05-10T00:00:00","deviceMetadataIds":null,"firmwareVersion":"0","deviceType":"external","isTestSign":false,"isFlightSign":false,"marketingNames":null,"selectedProductTypes":{"windows_v100_VB":"Unclassified"},"requestedSignatures":["WINDOWS_v100_X64_VB_FULL"],"additionalAttributes":null,"packageType":null}
Correlation Id: d1cc9a7c-280e-4977-a10b-16fd4a7c1f63
Return: -2 (UNHANDLED_EXCEPTION)
-1

Attestation Submission

> Create Product
* Create JSON
* Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
> Create Option
Unhandled Exception:
System.Net.Http.HttpRequestException: An error occurred while sending the reque
st. ---> System.Net.WebException: The underlying connection was closed: An unex
pected error occurred on a receive. ---> System.IO.IOException: Unable to read
data from the transport connection: An existing connection was forcibly closed
by the remote host. ---> System.Net.Sockets.SocketException: An existing connec
tion was forcibly closed by the remote host
at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, T
ransportContext& context)
at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult a
r)
--- End of inner exception stack trace ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at Microsoft.Devices.HardwareDevCenterManager.Utility.AuthorizationHandler.<
SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.
<InvokeHdcService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.
<InvokeHdcService>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.
<HdcPost>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.
<NewProduct>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in E:\Home\mtk
20241\Attestation_task\SDCM-main_1\SDCM-main\SurfaceDevCenterManager\Program.cs
:line 227
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNo
tification(Task task)
at SurfaceDevCenterManager.Program.Main(String[] args) in E:\Home\mtk20241\A
ttestation_task\SDCM-main_1\SDCM-main\SurfaceDevCenterManager\Program.cs:line 6
0
Last Command:
ERROR (DevCenterErrorDetails)
Code:
HttpCode:
Message:
Correlation Id: 66d7db57-d945-4979-bce1-0213252b764c
Request Id: 431a1487-6795-4830-aa08-75218d85f36c
Method: POST
Url: https://manage.devcenter.microsoft.com/v2.0/my/hardware/product
s
Content: {"productName":"mediatek_driver_Attestation","testHarness":"Att
estation","announcementDate":"2020-05-10T00:00:00","deviceMetadataIds":null,"fi
rmwareVersion":"0","deviceType":"external","isTestSign":false,"isFlightSign":fa
lse,"marketingNames":null,"selectedProductTypes":{"windows_v100_VB":"Unclassifi
ed"},"requestedSignatures":["WINDOWS_v100_x64_vb_FULL"],"additionalAttributes":
null,"packageType":null}
Correlation Id: 66d7db57-d945-4979-bce1-0213252b764c
Return: -2 (UNHANDLED_EXCEPTION)

**Comment by Ben-Carpenter** [comment] 2022-03-21 14:26
Duplicate of issue #32, the cause for the issue you are experiencing is the HttpRequestException. @MTKSDCM, please see the comments in #32.

**Closed by Ben-Carpenter** 2022-03-21 14:26 UTC
Labels: duplicate
